### ISSUE TITLE
GUI problem on windows 

### ISSUE THREAD

**Issue by ImDaWorst** [VivianoRiccardo/TOB-Too-Obvious-Bitch-LichessBot#3]
This is me from your video user named "blank" this is what the program looks like 

![25C33278-C3C8-4AB0-8EB3-4719DC5C9D0E](https://user-images.githubusercontent.com/30112196/72620024-f09d4c80-3957-11ea-9cf0-58d2ba899138.jpeg)

**Comment by VivianoRiccardo** [comment]
ok just made it resizible so if the widgets are cropped out you can manually resize the iinterface.
closing the issue.
